name: CI Pipeline - Windows

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on all branches

jobs:
  build-windows:
    name: Build on Windows with Visual Studio 2022
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Tests
        working-directory: build
        run: ctest -C Release --output-on-failure
